### ISSUE TITLE
Congratulations 👏👍

### ISSUE THREAD

**Issue by thorstenMueller** [nipponjo/tts-german-pytorch#1]
Guude (Hi) @nipponjo 👋,
i just want to say, congratulations for this impressive high quality trained german TTS model. I'm happy that my Thorsten-Voice dataset was useful for that.

**Comment by nipponjo** [comment]
Thank you @thorstenMueller. The datasets are really pleasant for training. I wish there were more people who would publish datasets like these 😄 .

**Comment by thorstenMueller** [comment]
I'm closing this issue, as it's no "issue", just a simple "Thank You" feedback 😊
